server:
   port: 8074 #can access the protected client endpoints

spring:
   application:
    name: spring-boot-admin-server
   boot:
    admin:
      client:
        url: http://localhost:8073
        instance:
          service-base-url: http://localhost:8073
          metadata:
               user.name: ${spring.security.user.name}
               user.password: ${spring.security.user.password}
        password: "admin"
        username:  "admin"
   profiles:
     active: secure

   security:
    user:
      name: "admin"
      password: "admin"


#mail notifications
#spring.mail.host=smtp.gmail.com
#spring.mail.username=test@gmail.com
#spring.mail.password=password
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#spring.boot.admin.notify.mail.to=test@gmail.com
#hipchat notifications
#spring.boot.admin.notify.hipchat.auth-token=<generated_token>
#spring.boot.admin.notify.hipchat.room-id=<room-id>
#spring.boot.admin.notify.hipchat.url=https://youcompany.hipchat.com/v2/